.TH GDMAP 1 "16 Oct 2005"
.SH NAME
gdmap -\ Graphical Disk Map

.SH SYNOPSIS
gdmap [\fB\-?\fR|\fB--help\fR]
      [\fB-f\fR \fIdir\fR|\fB--folder=\fR\fIdir\fR]

.SH DESCRIPTION

\fBGdMap\fR is a tool to display disk space using tree maps.
.LP

.SH OPTIONS

.IP "\fB\-?, \fB\-\-help\fR" 4
Prints the command line options.

.IP "\fB\-f \fR\fIdir\fR" 4
.PD 0
.IP "\fB\-\-folder=\fR\fIdir\fR" 4
Inspect directory after startup.

.SH BUGS
Please report bugs at http://sourceforge.net/projects/gdmap, if you
find any.

.SH AUTHORS
.TP
Markus Lausser (sgop@users.sourceforge.net)

